[package]
name = "tweet-at-compile-time"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[lib]
crate-type = ["dylib"]
plugin = true

[dependencies]
egg-mode = "0.11"
tokio-core = "0.1"
